services:
  backend:
    container_name: disculla-backend
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    env_file:
      - apps/backend/.env.docker
    ports:
      - "8080:8080"
    volumes:
      - ./apps/backend/src:/app/apps/backend/src
      - ./apps/backend/prisma:/app/apps/backend/prisma
    depends_on:
      - postgres

  frontend:
    container_name: disculla-frontend
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    env_file:
      - apps/frontend/.env
    ports:
      - "3000:3000"
    volumes:
      - ./apps/frontend/src:/app/apps/frontend/src
    depends_on:
      - backend

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    env_file:
      - db/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
